# Generated by Django 3.0.1 on 2020-09-25 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginactivity',
            name='user',
        ),
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 16, 20, 53, 525409)),
        ),
    ]
