# Generated by Django 3.0.1 on 2020-09-25 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jangoapp', '0002_auto_20200925_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 16, 21, 26, 130441)),
        ),
    ]
