# Generated by Django 3.0.1 on 2020-09-25 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jangoapp', '0003_auto_20200925_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 16, 55, 58, 526177)),
        ),
        migrations.AlterField(
            model_name='userloginactivity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
