# Generated by Django 3.0.1 on 2020-09-26 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jangoapp', '0004_auto_20200925_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 9, 19, 13, 955992)),
        ),
    ]
