# Generated by Django 3.0.1 on 2020-09-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jangoapp', '0005_auto_20200926_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
