# Generated by Django 3.0.1 on 2020-09-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jangoapp', '0006_delete_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activity_periods',
        ),
    ]
