# Generated by Django 3.0.1 on 2020-09-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jangoapp', '0007_delete_activity_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginactivity',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Success'), ('L', 'LOGOUT'), ('F', 'Failed')], default='S', max_length=1, null=True),
        ),
    ]
